### PR TITLE
Convert pages to typescript

### PR DESCRIPTION
**Pull request by aslaker**
I have converted all of the files in the `pages/` directory to Typescript.  This was a fairly easy lift as these files didn't have a ton of type issues right off the bat.  Below are a couple of callouts to pieces of code that I commented out due to type issues.  I can either fix that as part of this PR, or they can be fixed in a follow up.

1. Commented out the 'behavior' argument in the `window.scrollTo()` method on line 24 of `_app.tsx`.  This is currently set to a value of 'instant' which based on the type files is not a valid value.

2. Commented out all instances of `viewport='viewport'` as this is also not a valid value for this prop.  It looks like framer motion is looking for an object here that is of type `ViewportOptions`

*Keep in mind that Typescript is not always correct, and sometimes the types included with the external libraries are out of sync with what you are trying to accomplish.  If you think 'viewport' or 'behavior' is correct as is, then we may need to update the library to include their most recent types file.

### CODE REVIEW

**Comment by tr3mulant** [comment]
Regarding @aslaker callouts:
1. Looking up the details for the Window interface seems to indicate that the only accepted values are indeed "auto" and "smooth". The [Window.scollTo()](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo) says the behavior prop
   > Specifies whether the scrolling should animate smoothly (smooth), or happen instantly in a single jump (auto, the default value).
   
   To me, that seems to indicate that the intended use of the value `instant` was meant to mimic the default behavior (`behavior: 'auto'`). As the default behavior is `auto`, it seems like we can remove the line in question, no?
2.  [Framer Motion ViewPort Options](https://www.framer.com/docs/gestures/#viewport) details `viewport` prop takes an object instead of a string value. 
      ```javascript
      interface ViewportOptions {
          root?: RefObject<Element>;
          once?: boolean;
          margin?: string;
          amount?: "some" | "all" | number;
          fallback?: boolean;
      }
    ```
    Can we remove this line as default values for the viewport were being set instead of customized functionality?

I feel as though Typescript did exactly what we want it to do, let us know when we goofed. Checking out official documentation outside of `types.d.ts` for each package seems to corroborate what the TS magic tells us. 

What do you think, @calebn ?

**Comment by calebn** [comment]
@tr3mulant / @aslaker 

I spent a while trying to get the scroll behavior to work and using `instant` was the only value that seemed to work.

According to this [bug report](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1195) it looks like `instant` is no longer an officially supported value but both chrome and Firefox use it. There may be another work around for getting instant scrolling (I kept getting smooth scrolling to the top of the page which is unacceptable for page transitions).

**Comment by aslaker** [comment]
@tr3mulant I can go through and remove the viewport prop for now.

@calebn Have you tried "auto" yet for a value on the `scrollTo()` behavior?  If not, I can add that and we can test it out.  Otherwise, I can add a //@ts-ignore comment above that, which instructs Typescript to ignore the following line.  That is a valid solution when we have a workaround that Typescript doesn't know about.

**Comment by tr3mulant** [comment]
I'm good with this and ready to merge. Sound good?

**Comment by aslaker** [comment]
@tr3mulant Im good to merge if you guys are.

**Pull request merged**
